name: geopy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.4.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.2.1
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - cryptography=36.0.1
  - curl=7.82.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2022.2.1
  - dask-core=2022.2.1
  - distributed=2022.2.1
  - expat=2.4.7
  - fiona=1.8.21
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.30.0
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2022.2.0
  - gdal=3.4.2
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=69.1
  - idna=3.3
  - jbig=2.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.4.0
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgdal=3.4.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=14.2
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - locket=0.2.1
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.1
  - msgpack-python=1.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.7.1
  - nspr=4.32
  - nss=3.74
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - packaging=21.3
  - partd=1.2.0
  - pcre=8.45
  - pip=21.2.4
  - pixman=0.40.0
  - poppler=22.01.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=9.0.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.0
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - readline=8.1.2
  - requests=2.27.1
  - rtree=0.9.7
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - setuptools=58.0.4
  - shapely=1.8.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.38.0
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tiledb=2.7.1
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzcode=2022a
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wheel=0.37.1
  - xerces-c=3.2.3
  - xyzservices=2022.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - affine==2.3.0
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astroid==2.9.3
    - asttokens==2.0.5
    - babel==2.9.1
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cftime==1.6.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.8.3
    - flake8==4.0.1
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - isort==5.10.1
    - jedi==0.18.1
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-server==1.15.6
    - jupyterlab==3.3.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.11.2
    - jupyterthemes==0.20.0
    - lazy-object-proxy==1.7.1
    - lesscpy==0.15.0
    - llvmlite==0.38.0
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - nbclassic==0.3.7
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - netcdf4==1.5.8
    - notebook==6.4.10
    - notebook-shim==0.1.0
    - numba==0.55.1
    - owslib==0.25.0
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - platformdirs==2.5.1
    - ply==3.11
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycodestyle==2.8.0
    - pycrs==1.0.2
    - pyflakes==2.4.0
    - pygments==2.11.2
    - pylint==2.12.2
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - rasterio==1.2.10
    - rioxarray==0.10.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - snuggs==1.4.7
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - toml==0.10.2
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - wrapt==1.13.3
    - xarray==2022.3.0
    - xoak==0.1.1
